### ISSUE TITLE
Install on Linux ubuntu/Mint problems

### ISSUE THREAD

**Issue by seidlmic** [wudingcheng/TSAnalyzer#3]
Hello,
your soft looks promising as I have problems with old good GGMATLAB tools. But I was unable to install on W10 (Some C++ builder required, Python 3.8) neither Linux Mint (Python 3.4) not Ubuntu 18 (Python 3.6). Most promising was attempt on Ubuntu 18 with installing into venv.

I have installed required packages manually into venv with pip. The cvx* packages report some warnings with gcc build but finished with success. This is result.

`CVXcanon        0.1.1      
cvxopt          1.2.3      
cvxpy           1.0.25     
cycler          0.10.0     
dill            0.3.1.1    
ecos            2.0.7.post1
fastcache       1.1.0      
future          0.18.2     
kiwisolver      1.1.0      
matplotlib      3.1.2      
multiprocess    0.70.9     
numpy           1.17.4     
osqp            0.6.1      
pandas          0.25.3     
patsy           0.5.1      
pip             19.3.1     
pkg-resources   0.0.0      
pyparsing       2.4.5      
PySide2         5.12.1     
python-dateutil 2.8.1      
pytz            2019.3     
QtPy            1.9.0      
scipy           1.3.2      
scs             2.1.1.post2
setuptools      32.3.1     
shiboken2       5.12.1     
six             1.13.0     
statsmodels     0.10.1     
toolz           0.10.0`

When I try to run Python3 main.py I got some errors from Qt, that I managed to over come with little code modification. Unfortunately now I always finish with segmenation fault. As there is no hint where is a problem does anyone has same experience?

**Comment by wudingcheng** [comment]
Thanks for your interest.

For Python 3, [Anaconda ](https://anaconda.org/) is recommended.  The requirments for Qt packages and scientific packages have already been intergated in [Anaconda ](https://anaconda.org/). [Anaconda ](https://anaconda.org/) Support Win, Mac and Linux.

And The problems about cvx for Windows, you can download the pre-built packages from [Unofficial Windows Binaries for Python Extension Packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/).

If you have some questions, feel free to email me.

**Comment by wudingcheng** [comment]
Thanks for your interest.

For Python 3, [Anaconda ](https://anaconda.org/) is recommended.  The requirments for Qt packages and scientific packages have already been intergated in [Anaconda ](https://anaconda.org/). [Anaconda ](https://anaconda.org/) Support Win, Mac and Linux.

And The problems about cvx for Windows, you can download the pre-built packages from [Unofficial Windows Binaries for Python Extension Packages](https://www.lfd.uci.edu/~gohlke/pythonlibs/).

If you have some questions, feel free to email me.
